import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/patterns/Footer'
import HomeScreen from '@/screens/HomeScreen'


const inter = Inter({ subsets: ['latin'] })

const Title = ({ children, as }) => {
  const Tag = as
  return (
    <>
      <Tag>
        {children}
      </Tag>
      <style jsx>{`
        ${Tag} {
          color: red;
          font-family: sans-serif;
        }
      `}</style>
    </>
    
  )
}

export default HomeScreen

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Tour NextJS</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div>
        
//         <Title as="h1">Alura Cases - Home Page</Title>
//         <Link href="/faq">
//           Ir para FAQ
//         </Link>
//         <Footer/>
//       </div>
//     </>
//   )
// }